version: '3.1'

services:
  rides-service:
    build:
      context: rides
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - rides-db-docker
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rides-db-docker:5445/rides
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  rides-db-docker:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rides
      - PGPORT=5445
  driver-service:
    build:
      context: driver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - driver-db-docker
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://driver-db-docker:5444/driver
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  driver-db-docker:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=driver
      - PGPORT=5444
  passenger-service:
    build:
      context: passenger
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - passenger-db-docker
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://passenger-db-docker:5443/passenger
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  passenger-db-docker:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=passenger
      - PGPORT=5443
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE