version: '3.9'
services:
  driver-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=driver
    ports:
      - '5433:5432'
  passenger-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=passenger
    ports:
      - '5434:5432'
  rides-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rides
    ports:
      - '5435:5432'